### ISSUE TITLE
Rename portability.h

### ISSUE THREAD

**Issue by kazuho** [cybozu/libyrmcds#14]
It would be great if portability.h gets renamed to `yrmcds_portability.h` or something, since the file is internal to libyrmcds.

To use libyrmcds we need to add source directory of libyrmcds to the include paths (since it is the directory that contains yrmcds.h).  The existence of `portability.h` in the same directory means that there would be a conflict if user has a header file with the same name.

This is kind of a nit-pick (and I am not suffering from the issue).

**Comment by ymmt2005** [comment]
Sound reasonable.  I will rename it.  Thank you.
