### ISSUE TITLE
Portability on Solaris

### ISSUE THREAD

**Issue by fazalmajid** [cybozu/libyrmcds#15]
portability.h breaks on Solaris/SmartOS/Illumos as it assumes !(OSX || Linux) => BSD.
Solaris does not have sys/endian.h.
The patch below fixes this. I am using the macros {BE|LE}_IN{16|32|64} from Solaris' sys/byteorder.h which are a bit slower but can deal with unaligned access as the values might be read from a network buffer and not be guaranteed to be aligned on word boundaries.

    --- /home/majid/portability.h.dist  Fri Sep 11 11:56:21 2015
    +++ /home/majid/portability.h       Fri Sep 11 12:04:04 2015
    @@ -29,6 +29,20 @@
     #  define le64toh(x) OSSwapLittleToHostInt64(x)
     #elif defined(__linux__)
     #  include <endian.h>
    +#elif defined(sun) /* Solaris */
    +#  include <sys/byteorder.h>
    +#  define htobe16(x) BE_16(x)
    +#  define htole16(x) LE_16(x)
    +#  define be16toh(x) BE_IN16(x)
    +#  define le16toh(x) LE_IN16(x)
    +#  define htobe32(x) BE_32(x)
    +#  define htole32(x) LE_32(x)
    +#  define be32toh(x) BE_IN32(x)
    +#  define le32toh(x) LE_IN32(x)
    +#  define htobe64(x) BE_64(x)
    +#  define htole64(x) LE_64(x)
    +#  define be64toh(x) BE_IN64(x)
    +#  define le64toh(x) LE_IN64(x)
     #else // *BSD
     #  include <sys/endian.h>
     #endif

**Comment by ymmt2005** [comment]
@fazalmajid Thank you for the diff.  I will merge it soon.

**Comment by ymmt2005** [comment]
Fixed in #16.
@fazalmajid Sorry for the long delay!
