### ISSUE TITLE
Support text protocol

### ISSUE THREAD

**Issue by ymmt2005** [cybozu/libyrmcds#17]
Currently, libyrmcds supports binary protocol only.

To support text protocol as well, these may matter:

* Invalid keys (keys containing spaces and/or newlines).
* Non-existent commands.
* Differences in server response.

**Comment by ymmt2005** [comment]
## Design

### Keep API best for binary protocol.

Using text protocol can and will incur extra overheads and limitations.
In exchange, we keep the same API including response struct for both binary and text protocols.

### Mode of connection

memcached determines the connection mode by the first request from the client.
For this, the connection is only allowed to enter text protocol mode before sending
the first request.

### Request serials

As text protocol does not have opaque fields, request serials need to be emulated in libyrmcds.

If quiet flags were used, responses may or may not be returned from the server, which would
make us impossible to associate responses with requests.  For this, **use of quiet is not allowed
in the text protocol mode.**

This limitation comes from the API design that separates receives from sends.

### Invalid keys

Text protocol is vulnerable for illegal characters (white spaces and control characters) in keys.
If the connection is in text mode, API should return errors for such keys.

### Non-existent commands

If an API cannot be implemented with text protocol, the API should return an error.

**Comment by ymmt2005** [comment]
@kazuho Looks good?

**Comment by kazuho** [comment]
@ymmt2005 Thank you for spending time on this. Looks fantastic!

**Comment by ymmt2005** [comment]
One more unavoidable limitation...

Responses for `set`, `add`, or `replace` cannot set the correct CAS value.
Unlike binary protocol, text protocol does not bring CAS value in responses.
