### ISSUE TITLE
Clean way to shutdown the receiver thread?

### ISSUE THREAD

**Issue by kazuho** [cybozu/libyrmcds#8]
README.md states:
> Although the socket used in libyrmcds is blocking, receiving results from the server is separated from the sending operations. You can even use a different thread to receive results asynchronously.

The design is elegant, works like a charm.  However it seems like that there is no way to gracefully shutdown the receiver thread.

IMO, `yrmcds_recv` function should return (presumably with an error code like `YRMCDS_INTERRUPTED`) when `recv(2)` returns `EINTR`, so that applications can do whatever they want.

**Comment by kazuho** [comment]
FYI the code I am writing to integrate libyrmcds into H2O can be found within `kazuho/session-resumption-libyrmcds` branch of https://github.com/h2o/h2o (specifically [include/h2o/memcached.h](https://github.com/h2o/h2o/blob/kazuho/session-resumption-libyrmcds/include/h2o/memcached.h), [lib/common/memcached.c](https://github.com/h2o/h2o/blob/kazuho/session-resumption-libyrmcds/lib/common/memcached.c), [examples/libh2o/memcached.c](https://github.com/h2o/h2o/blob/kazuho/session-resumption-libyrmcds/examples/libh2o/memcached.c); note that it is still wip).

**Comment by kazuho** [comment]
Just a note, I agree that this is an enhancement issue.  For myself, for the standalone server of H2O I might not gracefully shutdown the memcached connection, as killing it would not harm things.  But for libh2o, it would be great if there could be a graceful shutdown method.

I also think that there could be clever workarounds for the issue; e.g. send a `NOOP` request when termination is required, and let the receiver shutdown itself when it receives a response to the request.

**Comment by ymmt2005** [comment]
You want to use signals to interrupt and notify the receiver thread, right?
Is the proposed specification (`YRMCDS_INTERRUPTED` for `EINTR`) just enough for you?

**Comment by kazuho** [comment]
> You want to use signals to interrupt and notify the receiver thread, right?

Yes.

> Is the proposed specification (YRMCDS_INTERRUPTED for EINTR) just enough for you?

I believe so.  I would like to write code like below once the library introduces the new flag.

```
static int term_received = 0;

/* signal handler to be registered by calling sigaction */
static void on_sigterm(int signo)
{
    ++term_received;
}

static void async_recv(yrmcds* c)
{
    yrmcds_response r;
    while(!term_received) {
        yrmcds_error e = yrmcds_recv(c, &r);
        if (e == YRMCDS_INTERRUPTED) {
            continue;
        } else if (e != YRMCDS_OK) {
            check_error(e);
            break;
        }
        /* handle the response */
        ...
    }
    /* do the cleanup */
    ...
}
```

**Comment by ymmt2005** [comment]
To work around this problem, `shutdown(SHUT_RD)` can be used too.
https://gist.github.com/ymmt2005/7c0ca977be998b52edc3

**Comment by ymmt2005** [comment]
To keep the same behavior between receive and send operations,
I want to keep the current implementation as the default behavior
for signal interruptions; i.e., `EINTR` is handled internally.

For those who want to handle `EINTR` by themselves, I'd like to
propose a new function `yrmcds_ignore_interrupt(yrmcds*)`.
Calling it disables internal `EINTR` handling so that receive and send
operations will return `YRMCDS_INTERRUPTED` error.

Still, as I personally do not like signals, I want to add another function
`yrmcds_shutdown(yrmcds*)` which simply calls `shutdown(SHUT_RD)`
on the socket.

**Comment by kazuho** [comment]
> To keep the same behavior between receive and send operations, I want to keep the current implementation as the default behavior for signal interruptions; i.e., `EINTR` is handled internally.
> 
> For those who want to handle `EINTR` by themselves, I'd like to propose a new function `yrmcds_set_interruptible(yrmcds*)`. Calling it disables internal `EINTR` handling so that receive and send operations will return `YRMCDS_INTERRUPTED` error upon interrupts by signals.

Sounds like a legitimate approach.

> Still, as I personally do not like signals, I want to add another function `yrmcds_shutdown(yrmcds*)` which simply calls `shutdown(SHUT_RD)` on the socket.

If you are to introduce `yrmcds_shutdown`, then I would not insist on using a signal for notification, as the only need I have now is to shutdown the receiver. I can simply use the shutdown function, and we can come back to discuss adding support for signals when we find actual need for them (i.e. interrupt for purposes other than stopping the receiver).

How does it sound?

**Comment by ymmt2005** [comment]
Good.  I will introduce just `yrmcds_shtudown`, leaving signal handling as it is for now.
